data:
  task: 'semisupervised'
  task_type: 'binary'
  batch_size: 32
  num_workers: 4
  pin_memory: true
  image_size: 224
  data_dir: 'data/processed/semisupervised/binary'
  percentage_labeled: 50 # Can be 100, 50, 10, or 1
  train_val_test_split: [0.7, 0.15, 0.15]
  augmentation:
    use_augmentation: true

model:
  architecture: 'resnet18'
  pretrained: true
  num_classes: 2  # Binary classification (2 classes: cat and dog)
  dropout_rate: 0.5

training:
  device: 'mps'
  num_epochs: 15
  learning_rate: 0.0001
  weight_decay: 0.0001
  optimizer: 'adam'
  scheduler: 'step'
  strategy: 'full'  # Options: 'full', 'last_layer', 'masked'
  unfreeze_layers: 1
  mixed_precision: false
  fast_mode: false

  # Early stopping configuration
  early_stopping:
    patience: 10
    min_delta: 0.0001
    monitor: 'val_loss'

  # Learning rate scheduler
  lr_scheduler:
    use_scheduler: true
    type: "step"
    step_size: 3
    gamma: 0.5
    min_lr: 0.000001
    milestones: [5, 8, 11]
    warmup_epochs: 2

  pseudo_labeling:
    confidence_threshold: 0.96
    rampup_epochs: 8
    warmup_epochs: 5
    alpha: 0.5  # Weight for pseudo-labeled loss

logging:
  experiment_name: "binary_pseudo_label_50"
  log_dir: "logs"
  tensorboard: true
  wandb: true
  wandb_project: "results-binary-pseudo-runs"
  wandb_entity: "axelberglund98-kth-royal-institute-of-technology"
  log_interval: 20
  checkpoint_dir: "checkpoints"  # Added checkpoint directory configuration
  save_dir: 'checkpoints/binary_pseudo_labeling'
  save_interval: 5 # Save checkpoint every 5 epochs
  log_level: 'detailed'  # Options: 'debug', 'detailed', 'info', 'warning', 'error'
  metrics:
    - accuracy
    - f1_score
    - precision
    - recall
    - confusion_matrix
    - pseudo_label_confidence
    - pseudo_label_ratio
    - labeled_data_ratio
    - unlabeled_data_ratio
    - learning_rate
    - batch_time
    - epoch_time

